[project]
name = "bb8-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cv-bridge>=1.13.0.post0",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "rospy>=1.15.11",
]
